# Generated by Django 5.2 on 2025-05-06 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_diaryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='created_at',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
