# Generated by Django 5.2 on 2025-05-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_goal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='long_term_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='short_term_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
