# Generated by Django 5.2.1 on 2025-05-09 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_diaryentry_user_alter_diaryentry_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('tasks', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='diaryentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
